#!/bin/sh
# list-wallpapers.sh
#
# One line per image directly under ~/Pictures/wall, name-sorted, as two
# TAB-separated fields:
#
#     <source-path>\t<thumbnail-path>
#
# The source path is the real wallpaper (what the picker sets and themes from);
# the thumbnail path is a small cached JPEG under ~/.cache/wal/thumbs that
# WallpaperPicker.qml paints in the grid so it loads instantly instead of
# decoding the full-res original every open. The thumbnails are generated by
# wal-prepare.sh (keyed by md5 of the realpath, the same KEY it uses for the
# tile/palette cache) and pre-warmed in bulk by wal-prepare-all.sh; if one
# isn't there yet, the thumbnail field falls back to the source itself so the
# grid still shows something (just a slower first decode).
#
# Rerun on a short poll while the picker is open (see WallpaperPicker.qml) so a
# newly-dropped-in image — and a just-generated thumbnail — show up without
# restarting anything. NOTE: consumers that only want the source path must read
# the first TAB field (see wal-prepare-all.sh).

DIR="$HOME/Pictures/wall"
THUMBS="$HOME/.cache/wal/thumbs"
[ -d "$DIR" ] || exit 0

find "$DIR" -maxdepth 1 -type f \( \
    -iname '*.png'  -o -iname '*.jpg' -o -iname '*.jpeg' \
    -o -iname '*.webp' -o -iname '*.bmp' \
    \) | sort | while IFS= read -r img; do
    real="$(realpath "$img")"
    key="$(printf '%s' "$real" | md5sum | cut -d' ' -f1)"
    thumb="$THUMBS/$key.jpg"
    [ -f "$thumb" ] || thumb="$img"
    printf '%s\t%s\n' "$img" "$thumb"
done
