#!/usr/bin/env bash
# wal-prepare-all.sh
#
# Runs wal-prepare.sh on every image under ~/Pictures/wall, so by the time you
# flip to one in quickshell's WallpaperPicker its tile/theme cache is already
# warm and wal-set.sh just has to apply it. Triggered by wal-prepare.path
# whenever that directory changes (a new image dropped in), and once at
# Hyprland startup to backfill anything already there.
set -u

# list-wallpapers.sh emits "source<TAB>thumbnail"; we only want the source. (Its
# thumbnails are generated by wal-prepare.sh itself, so reading field 1 and
# letting wal-prepare warm everything — mode/tile/palette AND the thumbnail — is
# exactly right.)
"$HOME/.config/quickshell/scripts/list-wallpapers.sh" | while IFS="$(printf '\t')" read -r img _; do
    [ -n "$img" ] && "$HOME/.config/scripts/wal-prepare.sh" "$img"
done
